### ISSUE TITLE
Best way to invoke?

### ISSUE THREAD

**Issue by IHOPKCdavidgagne** [Coding-Ninja/osTicketExporter#1]
I'm having trouble getting this to work, not sure what I'm doing wrong.

I just made a simple html to call the javascript but I get nothing back, not even an error.

Maybe you could provide some simple instructions for end users - Step 1, copy to server, step 2, modify exporter.js DB info, step 3, push button.

**Comment by starquake** [comment]
The contents of the javascript.js file look more like Python to me.

**Comment by danie-dejager** [comment]
It is python2.

**Comment by Coding-Ninja** [comment]
really sorry @IHOPKCdavidgagne this has now been fixed, yes I know its 5 years to late, but I er got busy :sweat_smile:
